-- Enable UUID extension (optional, but good practice)
create extension if not exists "uuid-ossp";

-- 1. Table Students (Mahasiswa)
create table public.students (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  nim text unique not null,
  name text not null,
  prodi text,
  username text unique not null,
  password text not null, -- Note: In real app, store hashed passwords!
  is_verified boolean default false
);

-- 2. Table Admins (Admin Pengelola)
create table public.admins (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  username text unique not null,
  password text not null,
  name text default 'Admin'
);

-- 3. Insert Default Admin
insert into public.admins (username, password, name)
values ('admin', 'admin123', 'Super Admin');

-- 4. Insert Sample Student (Optional)
insert into public.students (nim, name, prodi, username, password, is_verified)
values ('202415678', 'Abas Nugraha fratama', 'Al Quran dan Tafsir', '202415678', 'password123', true);

-- Enable Row Level Security (RLS) - Optional but recommended
alter table public.students enable row level security;
alter table public.admins enable row level security;

-- Create policies (Simplest allowed for development)
-- Allow anyone to read/write for now (You should restrict this in production!)
create policy "Allow public access to students" on public.students for all using (true);
create policy "Allow public access to admins" on public.admins for all using (true);
